
[functions.send-reminders]
enabled = true
verify_jwt = true
import_map = "./functions/send-reminders/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-reminders/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-reminders/*.html" ]

[functions.test-notifications]
enabled = true
verify_jwt = false
import_map = "./functions/test-notifications/deno.json"
entrypoint = "./functions/test-notifications/index.ts"
